- name: FTP Deployment
  # You may pin to the exact commit or the version.
  # uses: airvzxf/ftp-deployment-action@9efe025c218094bd451a0cb684d7cb471f4d9d4f
  uses: airvzxf/ftp-deployment-action@latest
  with:
    # FTP Server.
    server: 185.27.134.11
    # FTP User.
    user: unaux_28553267
    # FTP Password.
    password: 123abcABC@
    # Local directory.
    local_dir: # optional, default is ./
    # Remote directory.
    remote_dir: htdocs
    # Delete all the files inside of the remote directory.
    delete: # optional, default is false
    # Times that the lftp will be executed if an error occurred.
    max_retries: # optional, default is 10
    # Do not create symbolic links.
    no_symlinks: # optional, default is true
    # FTP - Allow SSL encryption.
    ftp_ssl_allow: # optional, default is false
    # FTP - FEAT: Determining what extended features the FTP server supports.
    ftp_use_feat: # optional, default is false
    # FTP - Delay in seconds between NOOP commands when downloading tail of a file.
    ftp_nop_interval: # optional, default is 2
    # NET - Maximum number of operation without success. 0 unlimited. 1 no retries.
    net_max_retries: # optional, default is 1
    # NET - Ignore hard errors. When reply 5xx errors or there is too many users.
    net_persist_retries: # optional, default is 5
    # NET - Sets the network protocol timeout.
    net_timeout: # optional, default is 15s
    # DNS - 0 no limit trying to lookup an address otherwise try only this number of times.
    dns_max_retries: # optional, default is 8
    # DNS - Time for DNS queries. Set to "never" to disable.
    dns_fatal_timeout: # optional, default is 10s
